"""C#/.NET prototype suite for the language-expansion study (#153).

The same four-project SDK-style graph is built three ways:

* ``dotnet``       -- the incumbent: ``dotnet build`` with MSBuild's own
                      incremental state, node reuse and compiler server;
* ``frost-dotnet`` -- an incumbent-owned boundary: one Frost command target
                      wrapping that same ``dotnet build``;
* ``frost-csc``    -- a generated command boundary: MSBuild evaluates each
                      project once (a design-time ``Compile`` with
                      ``SkipCompilerExecution``), and the generator turns the
                      exact Roslyn argv it would have used into one Frost
                      action per project, with the compiler, reference
                      assemblies and analyzers copied into the workspace as
                      declared inputs.

Every timed build is followed by executing the application and checking the
printed total, so a stale artifact fails the run instead of being timed. The
suite also runs untimed correctness probes (a public-API dependency change and,
for the generated boundary, a toolchain-closure change) and records which
actions actually executed, from Frost's own build event stream.

``docs/32_language_expansion.md`` explains what the numbers do and do not
support.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import shutil
import statistics
import subprocess
import tempfile
import time
from typing import Any

from frost_bench import (
    environment_snapshot,
    parse_csv,
    summarize,
    tool_specs,
    utc_now,
)

CSHARP_SCHEMA = "frost-bench-csharp-v1"
CSHARP_SCENARIOS = ("clean", "noop", "incremental_leaf", "incremental_shared")
CSHARP_TOOLS = ("frost-csc", "frost-csc-shared", "frost-dotnet", "dotnet")
# Frontends that run Frost's generated per-project csc actions.
GENERATED_TOOLS = ("frost-csc", "frost-csc-shared")
# Dependency order matters: a project may only reference an earlier one.
CSHARP_PROJECTS = ("Core", "Model", "Service", "App")
CSHARP_REFERENCES = {
    "Core": (),
    "Model": ("Core",),
    "Service": ("Model", "Core"),
    "App": ("Service",),
}
CSHARP_VALUE_BASE = {"Core": 0, "Model": 1000, "Service": 2000, "App": 3000}
CSHARP_TARGET_FRAMEWORK = "net10.0"
CSHARP_CONFIGURATION = "Release"
JVM_PROBE_TOOLS = ("javac", "kotlinc")

# The build properties every frontend shares. `DebugType=none` keeps the PDB
# path -- which differs between an MSBuild `obj/` tree and a Frost output tree
# -- out of the assembly, so the equal-artifact check can compare bytes rather
# than trusting a successful exit. PDB production is follow-up work, named in
# docs/32, not an omission this suite hides.
DIRECTORY_BUILD_PROPS = """<Project>
  <!-- Generated by frost_bench_csharp.py (#153). Shared by every frontend. -->
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory).dotnet/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory).dotnet/bin/$(MSBuildProjectName)/</BaseOutputPath>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <DebugType>none</DebugType>
    <UseAppHost>false</UseAppHost>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
"""


# ---------------------------------------------------------------------------
# Source graph


def csharp_value_class(project: str, index: int) -> str:
    return f"{project}Value{index:03d}"


def csharp_values(size: int) -> dict[str, list[int]]:
    return {
        project: [CSHARP_VALUE_BASE[project] + index for index in range(size)]
        for project in CSHARP_PROJECTS
    }


def csharp_expected_total(values: dict[str, list[int]], extra: int = 0) -> int:
    """What the application prints: every value once, plus Service's direct
    use of ``CoreValue000`` (the edge that makes the graph a diamond), plus
    whatever a correctness probe added."""
    return sum(sum(project_values) for project_values in values.values()) + values["Core"][0] + extra


def csharp_sources(size: int) -> list[str]:
    sources = []
    for project in CSHARP_PROJECTS:
        sources.extend(
            f"src/{project}/{csharp_value_class(project, index)}.cs"
            for index in range(size)
        )
        sources.append(
            f"src/{project}/Program.cs" if project == "App" else f"src/{project}/{project}Total.cs"
        )
    sources.append("src/Core/CoreConstants.cs")
    return sorted(sources)


def write_csharp_constants(root: pathlib.Path, offset: int) -> None:
    """A public constant Model reads. C# inlines constants into the consumer's
    IL, so a change here is only correct if every consumer recompiles -- the
    classic stale-constant trap an API-level compile-avoidance scheme must not
    fall into."""
    (root / "src/Core/CoreConstants.cs").write_text(
        "\n".join(
            [
                "namespace Bench.Core;",
                "",
                "public static class CoreConstants",
                "{",
                f"    public const ulong Offset = {offset}UL;",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_csharp_value(root: pathlib.Path, project: str, index: int, value: int) -> None:
    name = csharp_value_class(project, index)
    (root / "src" / project / f"{name}.cs").write_text(
        "\n".join(
            [
                f"namespace Bench.{project};",
                "",
                f"public static class {name}",
                "{",
                f"    public static ulong Get() => {value}UL;",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_csharp_aggregate(root: pathlib.Path, project: str, size: int) -> None:
    additions = [
        f"        total += {csharp_value_class(project, index)}.Get();"
        for index in range(size)
    ]
    upstream = {
        "Core": [],
        "Model": [
            "        total += Bench.Core.CoreTotal.Sum();",
            "        total += Bench.Core.CoreConstants.Offset;",
        ],
        "Service": [
            "        total += Bench.Model.ModelTotal.Sum();",
            "        total += Bench.Core.CoreValue000.Get();",
        ],
    }
    if project == "App":
        (root / "src/App/Program.cs").write_text(
            "\n".join(
                [
                    "namespace Bench.App;",
                    "",
                    "public static class Program",
                    "{",
                    "    public static int Main()",
                    "    {",
                    "        ulong total = Bench.Service.ServiceTotal.Sum();",
                    *additions,
                    "        System.Console.WriteLine(total);",
                    "        return 0;",
                    "    }",
                    "}",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        return
    (root / "src" / project / f"{project}Total.cs").write_text(
        "\n".join(
            [
                f"namespace Bench.{project};",
                "",
                f"public static class {project}Total",
                "{",
                "    public static ulong Sum()",
                "    {",
                "        ulong total = 0;",
                *upstream[project],
                *additions,
                "        return total;",
                "    }",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_csharp_project_file(root: pathlib.Path, project: str) -> None:
    lines = ['<Project Sdk="Microsoft.NET.Sdk">']
    if project == "App":
        lines.extend(
            [
                "  <PropertyGroup>",
                "    <OutputType>Exe</OutputType>",
                "  </PropertyGroup>",
            ]
        )
    references = CSHARP_REFERENCES[project]
    if references:
        lines.append("  <ItemGroup>")
        lines.extend(
            f'    <ProjectReference Include="../{reference}/{reference}.csproj" />'
            for reference in references
        )
        lines.append("  </ItemGroup>")
    lines.extend(["</Project>", ""])
    (root / "src" / project / f"{project}.csproj").write_text("\n".join(lines), encoding="utf-8")


def generate_csharp_sources(root: pathlib.Path, size: int) -> None:
    """Write the frontend-independent part of a workspace: projects and C#."""
    if root.exists():
        shutil.rmtree(root)
    for project in CSHARP_PROJECTS:
        (root / "src" / project).mkdir(parents=True)
        write_csharp_project_file(root, project)
        for index, value in enumerate(csharp_values(size)[project]):
            write_csharp_value(root, project, index, value)
        write_csharp_aggregate(root, project, size)
    write_csharp_constants(root, 0)
    (root / "Directory.Build.props").write_text(DIRECTORY_BUILD_PROPS, encoding="utf-8")
    (root / ".frostignore").write_text(".dotnet/\n", encoding="utf-8")


def csharp_source_digest(root: pathlib.Path) -> str:
    digest = hashlib.sha256()
    for relative in sorted(
        path.relative_to(root).as_posix()
        for path in root.glob("src/**/*")
        if path.is_file() and path.suffix in (".cs", ".csproj")
    ):
        digest.update(relative.encode() + b"\0" + (root / relative).read_bytes() + b"\0")
    return digest.hexdigest()


def csharp_graph_contract(size: int) -> dict[str, Any]:
    payload = json.dumps(
        {
            "projects": list(CSHARP_PROJECTS),
            "references": {key: list(value) for key, value in CSHARP_REFERENCES.items()},
            "sources": csharp_sources(size),
            "values": csharp_values(size),
            "target_framework": CSHARP_TARGET_FRAMEWORK,
            "configuration": CSHARP_CONFIGURATION,
            "directory_build_props": DIRECTORY_BUILD_PROPS,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode()
    return {
        "language": "C#",
        "shape": "four-project diamond (App -> Service -> Model -> Core, Service -> Core)",
        "project_count": len(CSHARP_PROJECTS),
        "project_reference_edges": sum(len(value) for value in CSHARP_REFERENCES.values()),
        "source_count": len(csharp_sources(size)),
        "value_files_per_project": size,
        "initial_expected_stdout": str(csharp_expected_total(csharp_values(size))),
        "contract_sha256": hashlib.sha256(payload).hexdigest(),
        "same_source_graph": True,
        "incremental_leaf": "one method body in the top App project changes",
        "incremental_shared": (
            "one method body in the bottom Core project changes; its public API "
            "(reference assembly) does not"
        ),
    }


# ---------------------------------------------------------------------------
# Toolchain


def dotnet_environment(state_root: pathlib.Path) -> dict[str, str]:
    """The environment every .NET process in this suite gets.

    CLI home and the NuGet folder are isolated under the benchmark work
    directory so a run neither reads nor writes the user's ~/.dotnet or
    ~/.nuget. The graph has no package references, so restore never touches
    the network."""
    environment = os.environ.copy()
    environment.update(
        {
            "DOTNET_CLI_TELEMETRY_OPTOUT": "1",
            "DOTNET_NOLOGO": "1",
            "DOTNET_SKIP_FIRST_TIME_EXPERIENCE": "1",
            "DOTNET_GENERATE_ASPNET_CERTIFICATE": "false",
            "DOTNET_CLI_HOME": (state_root / "dotnet-home").as_posix(),
            "NUGET_PACKAGES": (state_root / "nuget-packages").as_posix(),
        }
    )
    return environment


def find_dotnet() -> str | None:
    configured = os.environ.get("DOTNET_BIN")
    if configured:
        return configured if pathlib.Path(configured).is_file() else None
    return shutil.which("dotnet")


def dotnet_info(dotnet: str, environment: dict[str, str]) -> dict[str, Any] | None:
    """SDK version, the SDK directory and the targeting pack the SDK uses."""
    try:
        version = subprocess.check_output(
            [dotnet, "--version"], text=True, env=environment, stderr=subprocess.STDOUT
        ).strip()
    except (OSError, subprocess.SubprocessError):
        return None
    root = pathlib.Path(dotnet).resolve().parent
    sdk = root / "sdk" / version
    roslyn = sdk / "Roslyn" / "bincore"
    if not (roslyn / "csc.dll").is_file():
        return None
    packs = sorted((root / "packs/Microsoft.NETCore.App.Ref").glob("*"))
    runtimes = sorted((root / "shared/Microsoft.NETCore.App").glob("*"))
    return {
        "dotnet": pathlib.Path(dotnet).resolve().as_posix(),
        "dotnet_root": root.as_posix(),
        "sdk_version": version,
        "sdk_dir": sdk.as_posix(),
        "roslyn_dir": roslyn.as_posix(),
        "targeting_pack_versions": [path.name for path in packs],
        "runtime_versions": [path.name for path in runtimes],
    }


def run_checked(
    command: list[str],
    cwd: pathlib.Path,
    environment: dict[str, str],
) -> str:
    completed = subprocess.run(
        command,
        cwd=cwd,
        env=environment,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode != 0:
        tail = "\n".join(completed.stdout.splitlines()[-40:])
        raise RuntimeError(f"{' '.join(command)} failed with exit {completed.returncode}:\n{tail}")
    return completed.stdout


def dotnet_restore(root: pathlib.Path, dotnet: str, environment: dict[str, str]) -> None:
    run_checked(
        [dotnet, "restore", "src/App/App.csproj", "-nologo", "-v:q"],
        root,
        environment,
    )


# ---------------------------------------------------------------------------
# The generated command boundary


def design_time_compile_args(
    root: pathlib.Path,
    project: str,
    dotnet: str,
    environment: dict[str, str],
) -> list[str]:
    """The exact csc argv MSBuild would use for ``project``, without compiling.

    This is the design-time build IDEs use: ``SkipCompilerExecution`` runs the
    Csc task without invoking the compiler, and ``ProvideCommandLineArgs``
    returns its argv. ``BuildProjectReferences=false`` keeps it to one
    project; references still resolve to their (future) reference-assembly
    paths. The intermediate directory is cleared first because an up-to-date
    CoreCompile does not run the task at all and so reports nothing."""
    intermediate = root / ".dotnet/obj" / project / CSHARP_CONFIGURATION
    if intermediate.exists():
        shutil.rmtree(intermediate)
    output = run_checked(
        [
            dotnet,
            "msbuild",
            f"src/{project}/{project}.csproj",
            "-nologo",
            "-t:Compile",
            f"-p:Configuration={CSHARP_CONFIGURATION}",
            "-p:BuildProjectReferences=false",
            "-p:SkipCompilerExecution=true",
            "-p:ProvideCommandLineArgs=true",
            "-getItem:CscCommandLineArgs",
        ],
        root,
        environment,
    )
    start = output.find("{")
    if start < 0:
        raise RuntimeError(f"MSBuild returned no item JSON for {project}:\n{output[-2000:]}")
    items = json.loads(output[start:])["Items"]["CscCommandLineArgs"]
    arguments = [item["Identity"] for item in items]
    if not arguments:
        raise RuntimeError(f"MSBuild reported no compiler arguments for {project}")
    return arguments


def runtime_config_json(root: pathlib.Path, dotnet: str, environment: dict[str, str]) -> str:
    """The application's runtimeconfig.json, as MSBuild itself generates it."""
    run_checked(
        [
            dotnet,
            "msbuild",
            "src/App/App.csproj",
            "-nologo",
            # ResolveReferences supplies the framework reference; without it
            # the file names no framework and the host refuses to start.
            "-t:ResolveReferences;GenerateBuildRuntimeConfigurationFiles",
            f"-p:Configuration={CSHARP_CONFIGURATION}",
            "-p:BuildProjectReferences=false",
        ],
        root,
        environment,
    )
    matches = sorted(root.glob(".dotnet/bin/App/**/App.runtimeconfig.json"))
    if len(matches) != 1:
        raise RuntimeError(f"expected one generated App.runtimeconfig.json, found {len(matches)}")
    return matches[0].read_text(encoding="utf-8")


def _link_or_copy(source: pathlib.Path, destination: pathlib.Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        return
    try:
        os.link(source, destination)
    except OSError:
        shutil.copy2(source, destination)


def bundle_csharp_toolchain(
    root: pathlib.Path,
    info: dict[str, Any],
    files: set[pathlib.Path],
) -> dict[str, Any]:
    """Copy the compiler and every referenced SDK file into ``.dotnet-sdk``.

    Declared inputs are how a Frost action key sees bytes: the csc apphost is
    only a launcher, and the compiler that decides the output is csc.dll plus
    the Microsoft.CodeAnalysis assemblies beside it. The reference assemblies,
    analyzers and source generators the SDK passes are compiler inputs too --
    a source generator writes code into the assembly. So the whole closure
    lives in the workspace, hard-linked when the file system allows."""
    dotnet_root = pathlib.Path(info["dotnet_root"])
    bundle = root / ".dotnet-sdk"
    roslyn = pathlib.Path(info["roslyn_dir"])
    count = 0
    size = 0
    for path in sorted(roslyn.rglob("*")):
        if path.is_file():
            _link_or_copy(path, bundle / path.relative_to(dotnet_root))
            count += 1
            size += path.stat().st_size
    for path in sorted(files):
        _link_or_copy(path, bundle / path.relative_to(dotnet_root))
        count += 1
        size += path.stat().st_size
    return {"files": count, "bytes": size}


def translate_csc_arguments(
    root: pathlib.Path,
    project: str,
    arguments: list[str],
    info: dict[str, Any],
) -> tuple[list[str], list[str], list[str], set[pathlib.Path], list[tuple[pathlib.Path, str]]]:
    """Rewrite MSBuild's absolute, obj/-relative argv into a Frost action.

    Returns (args, source inputs, api dependencies, SDK files to bundle,
    generated files to copy). Anything this cannot classify is an error: a
    silently dropped argument would be a compiler input missing from the key.
    """
    dotnet_root = pathlib.Path(info["dotnet_root"]).resolve()
    workspace = root.resolve()
    obj = workspace / ".dotnet/obj"
    project_dir = workspace / "src" / project
    args: list[str] = []
    sources: list[str] = []
    dependencies: list[str] = []
    sdk_files: set[pathlib.Path] = set()
    generated: list[tuple[pathlib.Path, str]] = []

    def sdk_relative(path: pathlib.Path) -> str:
        sdk_files.add(path)
        return (pathlib.Path(".dotnet-sdk") / path.relative_to(dotnet_root)).as_posix()

    def generated_relative(path: pathlib.Path) -> str:
        destination = f".dotnet-gen/{project}/{path.name}"
        generated.append((path, destination))
        return destination

    for argument in arguments:
        # MSBuild writes options as `/name[:value]`; on POSIX an absolute
        # source path also starts with `/`, so a path that exists is a file.
        if argument.startswith("/") and pathlib.Path(argument).is_file():
            path = pathlib.Path(argument).resolve()
            if path.is_relative_to(obj):
                relative = generated_relative(path)
            elif path.is_relative_to(workspace):
                relative = path.relative_to(workspace).as_posix()
            else:
                raise RuntimeError(f"source {argument!r} of {project} lies outside the workspace")
            sources.append(relative)
            args.append(relative)
            continue
        option, separator, value = argument.partition(":")
        if argument.startswith("/") and separator and option in ("/out", "/refout"):
            continue
        if argument.startswith("/") and separator and option in (
            "/reference",
            "/analyzer",
            "/analyzerconfig",
        ):
            path = pathlib.Path(value).resolve()
            if path.is_relative_to(dotnet_root):
                args.append(f"{option}:{sdk_relative(path)}")
            elif option == "/reference" and path.is_relative_to(obj):
                referenced = path.relative_to(obj).parts[0]
                if referenced not in CSHARP_PROJECTS or path.name != f"{referenced}.dll":
                    raise RuntimeError(f"unrecognised project reference {value!r} in {project}")
                dependencies.append(referenced)
                args.append(f"/reference:.frost/out/${{config}}/api/{referenced}.dll")
            elif option == "/analyzerconfig" and path.is_relative_to(obj):
                args.append(f"/analyzerconfig:{generated_relative(path)}")
            else:
                raise RuntimeError(f"cannot place {option} input {value!r} for {project}")
            continue
        if argument.startswith("/"):
            args.append(argument)
            continue
        # A source file: relative to the project directory, or generated in obj/.
        path = (project_dir / argument).resolve()
        if path.is_relative_to(obj):
            relative = generated_relative(path)
        elif path.is_relative_to(workspace):
            relative = path.relative_to(workspace).as_posix()
        else:
            raise RuntimeError(f"source {argument!r} of {project} lies outside the workspace")
        sources.append(relative)
        args.append(relative)
    return args, sources, dependencies, sdk_files, generated


def toml_string(value: str) -> str:
    return json.dumps(value)


def toml_array(values: list[str], indent: str = "  ") -> str:
    if not values:
        return "[]"
    return "[\n" + "".join(f"{indent}{toml_string(value)},\n" for value in values) + "]"


def write_csharp_frost_generated(
    root: pathlib.Path,
    compile_args: dict[str, list[str]],
    info: dict[str, Any],
    runtime_config: str,
    *,
    shared: bool = False,
) -> dict[str, Any]:
    """Emit the generated command boundary: one csc action per project, one
    API-copy action per library, and the runtimeconfig beside the app.

    ``shared`` adds ``/shared``: each action's csc process hands the compile
    to Roslyn's compiler server (VBCSCompiler), started on first use from the
    bundled compiler and kept alive between actions and builds. That is the
    persistent worker MSBuild already uses, and the one question #145 asks of
    Frost; the server is outside Frost's process tree, action key and
    sandbox, which is exactly why it is a separate frontend."""
    translated = {}
    all_sdk_files: set[pathlib.Path] = set()
    for project in CSHARP_PROJECTS:
        args, sources, dependencies, sdk_files, generated = translate_csc_arguments(
            root, project, compile_args[project], info
        )
        for source, destination in generated:
            target = root / destination
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
        all_sdk_files |= sdk_files
        translated[project] = (args, sources, dependencies, [dest for _, dest in generated])
    bundle = bundle_csharp_toolchain(root, info, all_sdk_files)

    # Every project passes the same 160-odd reference assemblies, analyzers
    # and SDK analyzer configs. They go into one shared response file -- a
    # declared input, so its bytes are key material exactly as argv is --
    # instead of being repeated in every target.
    def closure_argument(argument: str) -> bool:
        option = argument.split(":", 1)[0]
        return option in ("/reference", "/analyzer", "/analyzerconfig") and ":.dotnet-sdk/" in argument

    closures = {
        project: [argument for argument in translated[project][0] if closure_argument(argument)]
        for project in CSHARP_PROJECTS
    }
    common_closure = closures[CSHARP_PROJECTS[0]]
    if any(closure != common_closure for closure in closures.values()):
        raise RuntimeError("projects disagree about the SDK reference closure; refusing to share it")
    response_file = ".dotnet-gen/sdk-closure.rsp"
    (root / response_file).parent.mkdir(parents=True, exist_ok=True)
    (root / response_file).write_text("\n".join(common_closure) + "\n", encoding="utf-8")
    for project in CSHARP_PROJECTS:
        args, sources, dependencies, generated = translated[project]
        compacted: list[str] = []
        for argument in args:
            if closure_argument(argument):
                if f"@{response_file}" not in compacted:
                    compacted.append(f"@{response_file}")
                continue
            compacted.append(argument)
        translated[project] = (compacted, sources, dependencies, [*generated, response_file])
    (root / ".dotnet-gen/App").mkdir(parents=True, exist_ok=True)
    (root / ".dotnet-gen/App/App.runtimeconfig.json").write_text(runtime_config, encoding="utf-8")

    csc = (
        pathlib.Path(".dotnet-sdk")
        / pathlib.Path(info["roslyn_dir"]).relative_to(info["dotnet_root"])
        / ("csc.exe" if os.name == "nt" else "csc")
    ).as_posix()
    lines = [
        "# Generated by frost_bench_csharp.py (#153): MSBuild evaluated each",
        "# project once; these are the Roslyn invocations it would have made.",
        f"# SDK {info['sdk_version']}; regenerate after changing any .csproj or",
        "# Directory.Build.props (the generator records their digest).",
        "",
        "[workspace]",
        'default_targets = ["app"]',
        "",
        "[toolchain.tools]",
        f"csc = {toml_string(csc)}",
        'cp = "cp"',
        "",
    ]
    environment = f'{{ DOTNET_ROOT = {toml_string(info["dotnet_root"])} }}'
    for project in CSHARP_PROJECTS:
        args, sources, dependencies, generated = translated[project]
        if project == "App":
            # Read by the copy step, so it is an input like any source: an
            # undeclared step input would be a cache key that cannot see it.
            generated = [*generated, ".dotnet-gen/App/App.runtimeconfig.json"]
        name = project.lower()
        outputs = [f".frost/out/${{config}}/bin/{project}.dll"]
        if project != "App":
            outputs.append(f".frost/out/${{config}}/ref/{project}.dll")
            refout = [f"/refout:.frost/out/${{config}}/ref/{project}.dll"]
        else:
            outputs.append(".frost/out/${config}/bin/App.runtimeconfig.json")
            refout = []
        lines.extend(
            [
                f"[target.{name}]",
                'kind = "command"',
                'tool = "csc"',
                f"deps = {toml_array([f'{dependency.lower()}_api' for dependency in dependencies])}",
                f"inputs = {toml_array(sorted(set(sources) | set(generated)) + ['.dotnet-sdk/**/*'])}",
                f"outputs = {toml_array(outputs)}",
                f"args = {toml_array(args + (['/shared'] if shared else []) + ['/out:${out}'] + refout)}",
            ]
        )
        if project == "App":
            lines.append(
                'steps = [{ tool = "cp", args = [".dotnet-gen/App/App.runtimeconfig.json", '
                '".frost/out/${config}/bin/App.runtimeconfig.json"] }]'
            )
        lines.extend([f"env = {environment}", "sandbox = false", ""])
        if project != "App":
            # Consumers compile against the reference assembly. Copying it is
            # the whole point: when an implementation-only edit leaves those
            # bytes unchanged, early cutoff stops here and no dependent project
            # recompiles -- MSBuild's ProduceReferenceAssembly avoidance,
            # expressed as an ordinary content-addressed edge.
            lines.extend(
                [
                    f"[target.{name}_api]",
                    'kind = "command"',
                    'tool = "cp"',
                    f'deps = ["{name}"]',
                    f'args = [".frost/out/${{config}}/ref/{project}.dll", "${{out}}"]',
                    f'outputs = [".frost/out/${{config}}/api/{project}.dll"]',
                    "sandbox = false",
                    "",
                ]
            )
    (root / "frost.toml").write_text("\n".join(lines), encoding="utf-8")
    stamp = {
        "sdk_version": info["sdk_version"],
        "evaluation_inputs_sha256": csharp_evaluation_digest(root),
    }
    (root / ".dotnet-gen/import-stamp.json").write_text(
        json.dumps(stamp, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return {"toolchain_bundle": bundle, "actions": len(CSHARP_PROJECTS) * 2 - 1}


def csharp_evaluation_digest(root: pathlib.Path) -> str:
    """Digest of what MSBuild evaluation reads: project files and props.

    A generated boundary is only as current as the evaluation it came from;
    ``verify_import_current`` refuses to time a build whose evaluation inputs
    changed after generation."""
    digest = hashlib.sha256()
    for path in sorted([root / "Directory.Build.props", *root.glob("src/*/*.csproj")]):
        digest.update(path.relative_to(root).as_posix().encode() + b"\0" + path.read_bytes())
    return digest.hexdigest()


def verify_import_current(root: pathlib.Path) -> None:
    stamp = json.loads((root / ".dotnet-gen/import-stamp.json").read_text(encoding="utf-8"))
    if stamp["evaluation_inputs_sha256"] != csharp_evaluation_digest(root):
        raise RuntimeError("project files changed after the generated boundary was imported")


def write_csharp_frost_wrapper(
    root: pathlib.Path,
    info: dict[str, Any],
    state_root: pathlib.Path,
    jobs: int,
) -> None:
    """One Frost action around the incumbent's whole ``dotnet build``."""
    environment = {
        "DOTNET_CLI_HOME": (state_root / "dotnet-home").as_posix(),
        "DOTNET_CLI_TELEMETRY_OPTOUT": "1",
        "DOTNET_NOLOGO": "1",
        "DOTNET_SKIP_FIRST_TIME_EXPERIENCE": "1",
        "NUGET_PACKAGES": (state_root / "nuget-packages").as_posix(),
    }
    lines = [
        "# Incumbent-owned boundary: MSBuild owns evaluation, restore state,",
        "# incrementality and the compiler server inside one Frost action.",
        "",
        "[workspace]",
        'default_targets = ["app"]',
        "",
        "[toolchain.tools]",
        f"dotnet = {toml_string(info['dotnet'])}",
        "",
        "[target.app]",
        'kind = "command"',
        'tool = "dotnet"',
        f"inputs = {toml_array(['Directory.Build.props', 'src/**/*.cs', 'src/**/*.csproj'])}",
        'output_dirs = [".frost/out/${config}/app"]',
        "args = "
        + toml_array(
            [
                "build",
                "src/App/App.csproj",
                "--no-restore",
                "-nologo",
                "-v:q",
                "-c",
                CSHARP_CONFIGURATION,
                f"-m:{max(1, jobs)}",
                "-o",
                "${output_dir}",
            ]
        ),
        "env = { "
        + ", ".join(f"{key} = {toml_string(value)}" for key, value in sorted(environment.items()))
        + " }",
        "sandbox = false",
        "",
    ]
    (root / "frost.toml").write_text("\n".join(lines), encoding="utf-8")


def generate_csharp_workspace(
    root: pathlib.Path,
    size: int,
    tool: str,
    info: dict[str, Any] | None,
    state_root: pathlib.Path,
    jobs: int = 1,
) -> dict[str, Any]:
    """Generate one frontend's workspace; returns import metadata.

    Without a .NET SDK only the sources are written, so the graph contract is
    still checkable (and unit-testable) on a host that cannot run it."""
    generate_csharp_sources(root, size)
    if info is None:
        return {}
    environment = dotnet_environment(state_root)
    dotnet_restore(root, info["dotnet"], environment)
    if tool in GENERATED_TOOLS:
        start = time.perf_counter()
        compile_args = {
            project: design_time_compile_args(root, project, info["dotnet"], environment)
            for project in CSHARP_PROJECTS
        }
        runtime_config = runtime_config_json(root, info["dotnet"], environment)
        import_ms = (time.perf_counter() - start) * 1000
        metadata = write_csharp_frost_generated(
            root, compile_args, info, runtime_config, shared=tool == "frost-csc-shared"
        )
        # The design-time evaluation leaves obj/ and bin/ state behind; none of
        # it is a Frost input, and the timed builds must not inherit it.
        shutil.rmtree(root / ".dotnet/bin", ignore_errors=True)
        metadata["import_ms"] = round(import_ms, 3)
        metadata["compiler_arguments"] = {
            project: len(arguments) for project, arguments in compile_args.items()
        }
        return metadata
    if tool == "frost-dotnet":
        write_csharp_frost_wrapper(root, info, state_root, jobs)
        return {}
    if tool == "dotnet":
        return {}
    raise ValueError(f"unsupported C# benchmark tool: {tool}")


# ---------------------------------------------------------------------------
# Running, cleaning, validating


def csharp_artifact_dir(root: pathlib.Path, tool: str) -> pathlib.Path:
    if tool == "dotnet":
        return root / ".dotnet/bin/App" / CSHARP_CONFIGURATION / CSHARP_TARGET_FRAMEWORK
    pattern = ".frost/out/*/bin" if tool in GENERATED_TOOLS else ".frost/out/*/app"
    matches = sorted(path for path in root.glob(pattern) if path.is_dir())
    if len(matches) != 1:
        raise RuntimeError(f"{tool}: expected one artifact directory matching {pattern}, found {len(matches)}")
    return matches[0]


def clean_csharp_outputs(root: pathlib.Path, tool: str) -> None:
    """Remove build outputs and build state, keeping restore results.

    Restore is not part of any timed build (every frontend runs
    ``--no-restore`` or never restores), so ``project.assets.json`` stays."""
    if tool.startswith("frost-"):
        shutil.rmtree(root / ".frost", ignore_errors=True)
    shutil.rmtree(root / ".dotnet/bin", ignore_errors=True)
    for project in CSHARP_PROJECTS:
        shutil.rmtree(root / ".dotnet/obj" / project / CSHARP_CONFIGURATION, ignore_errors=True)


def csharp_build_command(
    tool: str,
    frost: str | None,
    info: dict[str, Any],
    jobs: int,
    events: pathlib.Path,
) -> list[str]:
    if tool.startswith("frost-"):
        if frost is None:
            raise FileNotFoundError("frost")
        return [
            frost,
            "build",
            "--workspace",
            ".",
            "--jobs",
            str(max(1, jobs)),
            "--no-tui",
            "--build-event-json",
            events.as_posix(),
        ]
    return [
        info["dotnet"],
        "build",
        "src/App/App.csproj",
        "--no-restore",
        "-nologo",
        "-v:q",
        "-c",
        CSHARP_CONFIGURATION,
        f"-m:{max(1, jobs)}",
    ]


def read_frost_events(events: pathlib.Path) -> dict[str, Any]:
    """Which actions ran, and for how long, from Frost's own event stream."""
    executed: list[str] = []
    action_ms = 0
    cached = 0
    elapsed = None
    if events.is_file():
        for line in events.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            event = json.loads(line)
            if event.get("event") == "action_finished":
                if event.get("cached"):
                    cached += 1
                else:
                    executed.append(event.get("desc", ""))
                    action_ms += int(event.get("duration_ms") or 0)
            elif event.get("event") == "build_finished":
                elapsed = event.get("elapsed_ms")
    return {
        "executed_actions": sorted(executed),
        "executed_action_ms": action_ms,
        "cached_actions": cached,
        "frost_elapsed_ms": elapsed,
    }


def compiled_projects(root: pathlib.Path, tool: str, before: dict[str, float]) -> list[str]:
    """Projects whose intermediate assembly MSBuild rewrote during a build."""
    if tool in GENERATED_TOOLS:
        return []
    return sorted(
        project for project, mtime in csharp_obj_mtimes(root).items() if before.get(project) != mtime
    )


def csharp_obj_mtimes(root: pathlib.Path) -> dict[str, float]:
    mtimes = {}
    for project in CSHARP_PROJECTS:
        path = (
            root / ".dotnet/obj" / project / CSHARP_CONFIGURATION / CSHARP_TARGET_FRAMEWORK / f"{project}.dll"
        )
        if path.is_file():
            mtimes[project] = path.stat().st_mtime_ns
    return mtimes


def run_csharp_tool(
    root: pathlib.Path,
    tool: str,
    frost: str | None,
    info: dict[str, Any],
    jobs: int,
    state_root: pathlib.Path,
) -> tuple[float, dict[str, Any]]:
    if tool in GENERATED_TOOLS:
        verify_import_current(root)
    events = state_root / f"events-{tool}.ndjson"
    if events.exists():
        events.unlink()
    before = csharp_obj_mtimes(root)
    command = csharp_build_command(tool, frost, info, jobs, events)
    environment = dotnet_environment(state_root)
    start = time.perf_counter()
    completed = subprocess.run(
        command,
        cwd=root,
        env=environment,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    elapsed_ms = (time.perf_counter() - start) * 1000
    if completed.returncode != 0:
        tail = "\n".join(completed.stdout.splitlines()[-40:])
        raise RuntimeError(f"{tool} failed with exit {completed.returncode}: {' '.join(command)}\n{tail}")
    observation: dict[str, Any] = {}
    if tool.startswith("frost-"):
        observation.update(read_frost_events(events))
    if tool not in GENERATED_TOOLS:
        observation["msbuild_compiled_projects"] = compiled_projects(root, tool, before)
    return elapsed_ms, observation


def verify_csharp_output(
    root: pathlib.Path,
    tool: str,
    expected_total: int,
    info: dict[str, Any],
    state_root: pathlib.Path,
) -> dict[str, Any]:
    """Run the application and fingerprint the assemblies it is made of."""
    directory = csharp_artifact_dir(root, tool)
    assemblies = {}
    for project in CSHARP_PROJECTS:
        path = directory / f"{project}.dll"
        if not path.is_file():
            raise RuntimeError(f"{tool} did not produce {project}.dll in {directory}")
        assemblies[f"{project}.dll"] = hashlib.sha256(path.read_bytes()).hexdigest()
    runtime_config = directory / "App.runtimeconfig.json"
    if not runtime_config.is_file():
        raise RuntimeError(f"{tool} did not produce App.runtimeconfig.json")
    completed = subprocess.run(
        [info["dotnet"], (directory / "App.dll").as_posix()],
        cwd=root,
        env=dotnet_environment(state_root),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0 or completed.stdout.strip() != str(expected_total):
        raise RuntimeError(
            f"{tool} application printed {completed.stdout.strip()!r} (exit "
            f"{completed.returncode}, stderr {completed.stderr.strip()[-400:]!r}); "
            f"expected {expected_total}"
        )
    semantic = hashlib.sha256(
        json.dumps(
            {
                "stdout": completed.stdout.strip(),
                "assemblies": sorted(assemblies),
                "runtimeconfig": json.loads(runtime_config.read_text(encoding="utf-8")),
            },
            sort_keys=True,
        ).encode()
    ).hexdigest()
    return {
        "stdout": completed.stdout.strip(),
        "assemblies_sha256": assemblies,
        "assembly_set_sha256": hashlib.sha256(
            json.dumps(assemblies, sort_keys=True).encode()
        ).hexdigest(),
        "semantic_sha256": semantic,
        "extra_files": sorted(
            path.name
            for path in directory.iterdir()
            if path.is_file() and path.name not in {*assemblies, "App.runtimeconfig.json"}
        ),
    }


def csharp_configuration_metrics(root: pathlib.Path, tool: str) -> dict[str, Any]:
    authored = ["Directory.Build.props", *[f"src/{p}/{p}.csproj" for p in CSHARP_PROJECTS]]
    files = list(authored)
    if tool.startswith("frost-"):
        files.append("frost.toml")
    texts = {path: (root / path).read_text(encoding="utf-8") for path in files}
    metrics: dict[str, Any] = {
        "files": files,
        "configuration_lines": sum(len(text.splitlines()) for text in texts.values()),
        "configuration_bytes": sum(len(text.encode()) for text in texts.values()),
        "authored_msbuild_lines": sum(len(texts[path].splitlines()) for path in authored),
        "authored_msbuild_bytes": sum(len(texts[path].encode()) for path in authored),
    }
    if tool.startswith("frost-"):
        metrics["frost_manifest_lines"] = len(texts["frost.toml"].splitlines())
        metrics["frost_manifest_bytes"] = len(texts["frost.toml"].encode())
        metrics["frost_manifest_is_generated"] = tool in GENERATED_TOOLS
    if tool in GENERATED_TOOLS:
        metrics["generated_toolchain_bundle_excluded_from_configuration_size"] = [
            ".dotnet-sdk",
            ".dotnet-gen",
        ]
    return metrics


def dotnet_tool_version(info: dict[str, Any], frost: str | None, tool: str) -> str | None:
    if tool == "dotnet":
        return f"dotnet SDK {info['sdk_version']}"
    if frost is None:
        return None
    try:
        output = subprocess.check_output([frost, "--version"], text=True, stderr=subprocess.STDOUT)
    except (OSError, subprocess.SubprocessError):
        return None
    return output.strip().splitlines()[0] if output.strip() else None


def roslyn_version(info: dict[str, Any], state_root: pathlib.Path) -> str | None:
    csc = pathlib.Path(info["roslyn_dir"]) / ("csc.exe" if os.name == "nt" else "csc")
    environment = dotnet_environment(state_root)
    environment["DOTNET_ROOT"] = info["dotnet_root"]
    try:
        output = subprocess.check_output(
            [csc.as_posix(), "-version"], text=True, env=environment, stderr=subprocess.STDOUT
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return output.strip() or None


# ---------------------------------------------------------------------------
# Correctness probes


def probe_dependency_api_change(
    root: pathlib.Path,
    tool: str,
    frost: str | None,
    info: dict[str, Any],
    jobs: int,
    state_root: pathlib.Path,
    values: dict[str, list[int]],
) -> dict[str, Any]:
    """Change a public constant in Core that Model inlines; touch nothing else.

    Core's reference assembly changes (the constant's value is metadata), so
    Model must recompile even though none of its sources changed. A frontend
    that reused Model's cached assembly would print the old total. Nothing
    above Model sees an API change, so Service and App may be skipped."""
    try:
        write_csharp_constants(root, 5)
        _, observation = run_csharp_tool(root, tool, frost, info, jobs, state_root)
        artifact = verify_csharp_output(
            root, tool, csharp_expected_total(values, extra=5), info, state_root
        )
        return {"status": "passed", "observed": observation, "stdout": artifact["stdout"]}
    except Exception as error:  # recorded in the report, never swallowed
        return {"status": "failed", "reason": str(error)}
    finally:
        write_csharp_constants(root, 0)
        run_csharp_tool(root, tool, frost, info, jobs, state_root)
        verify_csharp_output(root, tool, csharp_expected_total(values), info, state_root)


def probe_toolchain_closure_change(
    root: pathlib.Path,
    tool: str,
    frost: str | None,
    info: dict[str, Any],
    jobs: int,
    state_root: pathlib.Path,
    values: dict[str, list[int]],
) -> dict[str, Any]:
    """Change one byte-level input of the compiler closure (the SDK analysis
    level globalconfig every project passes) without touching any source.

    Every compile action must rerun: if the closure were not in the key, all
    four would be cache hits. The file is replaced, not edited in place,
    because it is hard-linked to the real SDK."""
    configs = sorted(root.glob(".dotnet-sdk/**/analysislevel*.globalconfig")) or sorted(
        root.glob(".dotnet-sdk/**/*.globalconfig")
    )
    if not configs:
        return {"status": "skipped", "reason": "no bundled globalconfig to change"}
    target = configs[0]
    original = target.read_bytes()
    try:
        target.unlink()
        target.write_bytes(original + b"\n# frost-bench toolchain probe\n")
        _, observation = run_csharp_tool(root, tool, frost, info, jobs, state_root)
        verify_csharp_output(root, tool, csharp_expected_total(values), info, state_root)
        compiled = [
            name for name in observation.get("executed_actions", []) if not name.rstrip("]").endswith("_api")
        ]
        return {
            "status": "passed" if len(compiled) == len(CSHARP_PROJECTS) else "failed",
            "changed_file": target.relative_to(root).as_posix(),
            "observed": observation,
            "compile_actions_rerun": len(compiled),
        }
    except Exception as error:
        return {"status": "failed", "reason": str(error)}
    finally:
        target.unlink(missing_ok=True)
        target.write_bytes(original)
        run_csharp_tool(root, tool, frost, info, jobs, state_root)


# ---------------------------------------------------------------------------
# JVM startup probe (evidence for the Kotlin decision)


def write_jvm_probe_sources(root: pathlib.Path, size: int) -> None:
    java = root / "java/bench"
    kotlin = root / "kotlin/bench"
    java.mkdir(parents=True)
    kotlin.mkdir(parents=True)
    for index in range(size):
        (java / f"Value{index:03d}.java").write_text(
            f"package bench;\n\npublic final class Value{index:03d} {{\n"
            f"    public static long get() {{ return {index}L; }}\n}}\n",
            encoding="utf-8",
        )
        (kotlin / f"Value{index:03d}.kt").write_text(
            f"package bench\n\nobject Value{index:03d} {{\n    fun get(): Long = {index}L\n}}\n",
            encoding="utf-8",
        )


def measure_jvm_compiler_startup(
    base: pathlib.Path,
    size: int,
    iterations: int,
) -> dict[str, Any]:
    """Cold one-shot compiles of the same N-class library by javac and kotlinc.

    This is not a Kotlin benchmark; it measures the per-invocation cost a
    native ``kotlinc`` rule would pay without a persistent worker, next to the
    javac cost Frost already pays for Java."""
    root = base / "jvm-probe"
    if root.exists():
        shutil.rmtree(root)
    write_jvm_probe_sources(root, size)
    compilers = {
        "javac": os.environ.get("JAVAC_BIN") or shutil.which("javac"),
        "kotlinc": os.environ.get("KOTLINC_BIN") or shutil.which("kotlinc"),
    }
    samples: dict[str, list[float]] = {name: [] for name in JVM_PROBE_TOOLS}
    results: dict[str, Any] = {}
    active = [name for name in JVM_PROBE_TOOLS if compilers[name]]
    for name in JVM_PROBE_TOOLS:
        if not compilers[name]:
            results[name] = {
                "status": "skipped",
                "reason": f"{name} not found; set {name.upper()}_BIN to include it",
            }

    def command(name: str, output: pathlib.Path) -> list[str]:
        if name == "javac":
            return [
                compilers["javac"],
                "--release",
                "21",
                "-d",
                output.as_posix(),
                *sorted(path.as_posix() for path in (root / "java/bench").glob("*.java")),
            ]
        return [
            compilers["kotlinc"],
            "-jvm-target",
            "21",
            "-no-reflect",
            "-d",
            output.as_posix(),
            *sorted(path.as_posix() for path in (root / "kotlin/bench").glob("*.kt")),
        ]

    for iteration in range(iterations + 1):
        order = active if iteration % 2 == 0 else list(reversed(active))
        for name in order:
            output = root / f"out-{name}"
            shutil.rmtree(output, ignore_errors=True)
            output.mkdir()
            start = time.perf_counter()
            completed = subprocess.run(
                command(name, output),
                cwd=root,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                check=False,
            )
            elapsed = (time.perf_counter() - start) * 1000
            if completed.returncode != 0:
                results[name] = {"status": "failed", "reason": completed.stdout[-1500:]}
                active = [tool for tool in active if tool != name]
                continue
            classes = len(list(output.rglob("*.class")))
            if classes < size:
                results[name] = {"status": "failed", "reason": f"only {classes} classes produced"}
                active = [tool for tool in active if tool != name]
                continue
            if iteration > 0:  # the first round warms the page cache only
                samples[name].append(elapsed)
    for name in active:
        version = subprocess.run(
            [compilers[name], "-version"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        ).stdout.strip()
        results[name] = {
            "status": "ok",
            "version": version.splitlines()[-1] if version else None,
            "classes": size,
            "cold_compile": summarize(samples[name]),
        }
    if all(results.get(name, {}).get("status") == "ok" for name in JVM_PROBE_TOOLS):
        results["kotlinc_over_javac_median"] = round(
            results["kotlinc"]["cold_compile"]["median_ms"] / results["javac"]["cold_compile"]["median_ms"],
            3,
        )
    return {
        "question": "per-invocation cost of a native kotlinc rule without a persistent worker",
        "sources_per_compiler": size,
        "warmup_rounds_discarded": 1,
        "execution_order": "alternating; reversed every round",
        "results": results,
    }


# ---------------------------------------------------------------------------
# Measurement


def measure_csharp_tools_interleaved(
    base_workdir: pathlib.Path,
    tools: list[str],
    frost: str | None,
    info: dict[str, Any] | None,
    size: int,
    iterations: int,
    jobs: int,
    selected_scenarios: tuple[str, ...],
    probes: bool,
) -> list[dict[str, Any]]:
    state_root = base_workdir / ".state"
    state_root.mkdir(parents=True, exist_ok=True)
    roots: dict[str, pathlib.Path] = {}
    values = {tool: csharp_values(size) for tool in tools}
    samples = {tool: {scenario: [] for scenario in selected_scenarios} for tool in tools}
    observations = {tool: {scenario: [] for scenario in selected_scenarios} for tool in tools}
    imports: dict[str, dict[str, Any]] = {}
    failures: dict[str, str] = {}
    skipped: dict[str, str] = {}
    active: list[str] = []

    for tool in tools:
        root = base_workdir / f"csharp-{tool}-{size}"
        roots[tool] = root
        if info is None:
            generate_csharp_workspace(root, size, tool, None, state_root)
            skipped[tool] = "dotnet SDK was not found; set DOTNET_BIN to include it"
            continue
        if tool.startswith("frost-") and frost is None:
            generate_csharp_workspace(root, size, tool, None, state_root)
            skipped[tool] = "frost executable was not found; set FROST_BIN to include it"
            continue
        try:
            imports[tool] = generate_csharp_workspace(root, size, tool, info, state_root, jobs)
            active.append(tool)
        except Exception as error:
            failures[tool] = f"generation failed: {error}"

    def ordered(iteration: int) -> list[str]:
        available = [tool for tool in active if tool not in failures]
        return available if iteration % 2 == 0 else list(reversed(available))

    def build_and_validate(tool: str, scenario: str | None) -> None:
        if tool in failures:
            return
        try:
            elapsed, observation = run_csharp_tool(roots[tool], tool, frost, info, jobs, state_root)
            verify_csharp_output(
                roots[tool], tool, csharp_expected_total(values[tool]), info, state_root
            )
            if scenario is not None:
                samples[tool][scenario].append(elapsed)
                observations[tool][scenario].append(observation)
        except Exception as error:
            failures[tool] = str(error)

    # One untimed build per frontend first: the first `dotnet` invocation after
    # generation pays for MSBuild/Roslyn JIT and starts the compiler server,
    # which the incumbent keeps warm for every later sample, as Gradle's daemon
    # is kept warm in docs/17.
    for tool in active:
        build_and_validate(tool, None)

    if "clean" in selected_scenarios:
        for iteration in range(iterations):
            for tool in ordered(iteration):
                try:
                    clean_csharp_outputs(roots[tool], tool)
                except Exception as error:
                    failures[tool] = str(error)
                    continue
                build_and_validate(tool, "clean")

    if "noop" in selected_scenarios:
        for tool in active:
            build_and_validate(tool, None)
        for iteration in range(iterations):
            for tool in ordered(iteration):
                build_and_validate(tool, "noop")

    for scenario, project in (("incremental_leaf", "App"), ("incremental_shared", "Core")):
        if scenario not in selected_scenarios:
            continue
        for tool in active:
            build_and_validate(tool, None)
        for iteration in range(iterations):
            for tool in ordered(iteration):
                if tool in failures:
                    continue
                index = size - 1
                values[tool][project][index] += 1
                write_csharp_value(roots[tool], project, index, values[tool][project][index])
                build_and_validate(tool, scenario)

    probe_results: dict[str, dict[str, Any]] = {tool: {} for tool in tools}
    if probes and info is not None:
        for tool in active:
            if tool in failures:
                continue
            probe_results[tool]["dependency_api_change"] = probe_dependency_api_change(
                roots[tool], tool, frost, info, jobs, state_root, values[tool]
            )
        for tool in GENERATED_TOOLS:
            if tool in active and tool not in failures:
                probe_results[tool]["toolchain_closure_change"] = probe_toolchain_closure_change(
                    roots[tool], tool, frost, info, jobs, state_root, values[tool]
                )

    results = []
    for tool in tools:
        if tool in skipped:
            results.append({"tool": tool, "size": size, "status": "skipped", "reason": skipped[tool], "scenarios": {}})
            continue
        if tool in failures:
            results.append({"tool": tool, "size": size, "status": "failed", "reason": failures[tool], "scenarios": {}})
            continue
        artifact = verify_csharp_output(
            roots[tool], tool, csharp_expected_total(values[tool]), info, state_root
        )
        scenario_results = {}
        for scenario in selected_scenarios:
            summary = summarize(samples[tool][scenario])
            summary["observed"] = observations[tool][scenario]
            if tool.startswith("frost-"):
                overheads = [
                    wall - observation["executed_action_ms"]
                    for wall, observation in zip(samples[tool][scenario], observations[tool][scenario])
                ]
                inner = [observation["executed_action_ms"] for observation in observations[tool][scenario]]
                summary["inner_action_median_ms"] = round(statistics.median(inner), 3) if inner else None
                summary["frost_boundary_overhead_median_ms"] = (
                    round(statistics.median(overheads), 3) if overheads else None
                )
            scenario_results[scenario] = summary
        results.append(
            {
                "tool": tool,
                "version": dotnet_tool_version(info, frost, tool),
                "size": size,
                "status": "ok",
                "iterations": iterations,
                "jobs": jobs,
                "artifact": artifact,
                "configuration": csharp_configuration_metrics(roots[tool], tool),
                "import": imports.get(tool, {}),
                "probes": probe_results[tool],
                "scenarios": scenario_results,
            }
        )
    return results


def run_csharp_benchmark(args: argparse.Namespace) -> dict[str, Any]:
    tools = parse_csv(args.tools, valid=CSHARP_TOOLS)
    requested = parse_csv(args.scenarios, valid=CSHARP_SCENARIOS)
    if not tools:
        raise SystemExit("--tools must select at least one C# frontend")
    if not requested:
        raise SystemExit("--scenarios must select at least one scenario")
    if args.size <= 0 or args.iterations <= 0 or args.jobs <= 0:
        raise SystemExit("--size, --iterations, and --jobs must be positive")
    selected = tuple(scenario for scenario in CSHARP_SCENARIOS if scenario in requested)
    environment = environment_snapshot()

    if args.workdir:
        base_workdir = pathlib.Path(args.workdir).resolve()
        base_workdir.mkdir(parents=True, exist_ok=True)
        temp_context = None
    else:
        temp_context = tempfile.TemporaryDirectory(prefix="frost-csharp-bench-")
        base_workdir = pathlib.Path(temp_context.name)

    frost_spec = tool_specs(["frost"])[0]
    frost = frost_spec.argv[0] if frost_spec.argv else None
    dotnet = find_dotnet()
    info = None
    if dotnet:
        (base_workdir / ".state").mkdir(parents=True, exist_ok=True)
        info = dotnet_info(dotnet, dotnet_environment(base_workdir / ".state"))
    compiler = roslyn_version(info, base_workdir / ".state") if info else None
    try:
        results = measure_csharp_tools_interleaved(
            base_workdir,
            tools,
            frost,
            info,
            args.size,
            args.iterations,
            args.jobs,
            selected,
            not args.no_probes,
        )
        jvm_probe = (
            measure_jvm_compiler_startup(base_workdir, args.size, args.jvm_probe_iterations)
            if args.jvm_probe_iterations > 0
            else None
        )
    finally:
        if temp_context is not None and not args.keep_workdir:
            temp_context.cleanup()
    environment["load_avg_after"] = list(os.getloadavg()) if hasattr(os, "getloadavg") else None

    successful = [result for result in results if result["status"] == "ok"]
    semantic = {result["tool"]: result["artifact"]["semantic_sha256"] for result in successful}
    assemblies = {result["tool"]: result["artifact"]["assembly_set_sha256"] for result in successful}
    return {
        "schema": CSHARP_SCHEMA,
        "suite": "csharp",
        "generated_at": utc_now(),
        "environment": environment,
        "config": {
            "tools": tools,
            "size": args.size,
            "iterations": args.iterations,
            "jobs": args.jobs,
            "scenarios": list(selected),
            "toolchain": {
                "sdk_version": info["sdk_version"] if info else None,
                "roslyn": compiler,
                "targeting_packs": info["targeting_pack_versions"] if info else None,
                "runtimes": info["runtime_versions"] if info else None,
                "target_framework": CSHARP_TARGET_FRAMEWORK,
                "configuration": CSHARP_CONFIGURATION,
            },
            "clean_policy": (
                "delete bin/ and the configuration's obj/ tree (and .frost for Frost "
                "frontends); restore results are kept and every timed build is --no-restore"
            ),
            "warm_policy": (
                "one untimed build per frontend before sampling; MSBuild node reuse and "
                "the Roslyn compiler server (VBCSCompiler) stay enabled for dotnet and "
                "frost-dotnet, which share one warm server; frost-csc runs each compile "
                "in a fresh csc process"
            ),
            "generated_boundary_policy": (
                "frost-csc: one MSBuild design-time Compile per project "
                "(SkipCompilerExecution + ProvideCommandLineArgs) yields the exact csc "
                "argv; the compiler, reference assemblies, analyzers and source generators "
                "are copied into .dotnet-sdk and declared as inputs; consumers compile "
                "against a copied reference assembly so implementation-only edits stop at "
                "early cutoff. The one-time import cost is reported separately, never "
                "folded into a timed build"
            ),
            "execution_order": "round-robin; reverse frontend order on every measured iteration",
        },
        "graph": csharp_graph_contract(args.size),
        "output_equivalence": {
            "comparison_unit": (
                "application stdout after every timed build, the exact assembly set, "
                "SHA-256 of every assembly, and runtimeconfig.json content"
            ),
            "validated_after_every_timed_build": True,
            "semantic_digests": semantic,
            "assembly_set_digests": assemblies,
            "semantic_equal": len(semantic) > 1 and len(set(semantic.values())) == 1,
            "byte_identical_assemblies": len(assemblies) > 1 and len(set(assemblies.values())) == 1,
        },
        "jvm_startup_probe": jvm_probe,
        "results": results,
    }


def add_csharp_parser(sub: Any, run_command: Any) -> None:
    parser = sub.add_parser(
        "csharp",
        help="compare a four-project C# graph through dotnet build and two Frost boundaries",
    )
    parser.add_argument("--tools", default=",".join(CSHARP_TOOLS))
    parser.add_argument("--size", type=int, default=25, help="value files per project")
    parser.add_argument(
        "--scenarios",
        default=",".join(CSHARP_SCENARIOS),
        help="comma-separated clean, noop, incremental_leaf, incremental_shared",
    )
    parser.add_argument("--iterations", type=int, default=7)
    parser.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 4) // 2))
    parser.add_argument(
        "--jvm-probe-iterations",
        type=int,
        default=0,
        help="also time cold javac/kotlinc compiles of the same-size library (0 = off)",
    )
    parser.add_argument("--no-probes", action="store_true", help="skip the correctness probes")
    parser.add_argument("--workdir", help="directory for generated workspaces")
    parser.add_argument("--keep-workdir", action="store_true")
    parser.add_argument("--out", help="write JSON report to this path as well as stdout")
    parser.set_defaults(func=run_command)
