#!/usr/bin/env python3
"""Render release-specific Homebrew and Scoop manifests from SHA256SUMS."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


VERSION = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
ARCHIVE = re.compile(r"^frostbuild-v(?P<version>[0-9]+\.[0-9]+\.[0-9]+)-(?P<triple>[^/]+)\.(?:tar\.gz|zip)$")
SHA256 = re.compile(r"^[0-9a-fA-F]{64}$")
BASE = "https://github.com/hjosugi/frost-build/releases/download"


def checksums(path: Path, version: str) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        fields = line.split()
        if len(fields) != 2:
            raise ValueError(f"{path}:{number}: expected SHA256 and asset name")
        digest, name = fields
        name = name.removeprefix("*")
        match = ARCHIVE.fullmatch(name)
        if not SHA256.fullmatch(digest):
            raise ValueError(f"{path}:{number}: invalid SHA-256")
        if not match or match.group("version") != version:
            raise ValueError(f"{path}:{number}: unexpected release asset {name!r}")
        if name in parsed:
            raise ValueError(f"{path}:{number}: duplicate release asset {name!r}")
        parsed[name] = digest.lower()
    return parsed


def asset(version: str, triple: str, suffix: str) -> str:
    return f"frostbuild-v{version}-{triple}.{suffix}"


def require(items: dict[str, str], name: str) -> str:
    try:
        return items[name]
    except KeyError as error:
        raise ValueError(f"SHA256SUMS has no required asset {name!r}") from error


def formula(version: str, items: dict[str, str]) -> str:
    linux = asset(version, "x86_64-unknown-linux-musl", "tar.gz")
    mac_arm = asset(version, "aarch64-apple-darwin", "tar.gz")
    mac_intel = asset(version, "x86_64-apple-darwin", "tar.gz")
    linux_sha = require(items, linux)
    arm_sha = items.get(mac_arm)
    intel_sha = items.get(mac_intel)
    if not arm_sha and not intel_sha:
        raise ValueError("SHA256SUMS has no supported macOS archive")

    mac_branches: list[str] = []
    if arm_sha:
        mac_branches.extend(
            [
                "    if Hardware::CPU.arm?",
                f'      url "{BASE}/v{version}/{mac_arm}"',
                f'      sha256 "{arm_sha}"',
            ]
        )
    if intel_sha:
        mac_branches.extend(
            [
                "    elsif Hardware::CPU.intel?" if arm_sha else "    if Hardware::CPU.intel?",
                f'      url "{BASE}/v{version}/{mac_intel}"',
                f'      sha256 "{intel_sha}"',
            ]
        )
    mac_branches.extend(
        [
            "    else",
            '      odie "FrostBuild publishes no archive for this macOS architecture"',
            "    end",
        ]
    )
    mac = "\n".join(mac_branches)
    return f'''# Generated by scripts/render_distribution_manifests.py; do not edit.
class Frostbuild < Formula
  desc "Correct, fast incremental build system"
  homepage "https://github.com/hjosugi/frost-build"
  version "{version}"
  license "0BSD"

  on_macos do
{mac}
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "{BASE}/v{version}/{linux}"
      sha256 "{linux_sha}"
    else
      odie "FrostBuild publishes no archive for this Linux architecture"
    end
  end

  def install
    bin.install "frost", "frostd"
    man1.install Dir["share/man/man1/*.1"]
    bash_completion.install "share/completions/frost.bash" => "frost"
    zsh_completion.install "share/completions/_frost"
    fish_completion.install "share/completions/frost.fish"
  end

  test do
    assert_match "frost {version}", shell_output("#{{bin}}/frost --version")
  end
end
'''


def scoop(version: str, items: dict[str, str]) -> str:
    windows = asset(version, "x86_64-pc-windows-msvc", "zip")
    digest = require(items, windows)
    manifest = {
        "version": version,
        "description": "Correct, fast incremental build system",
        "homepage": "https://github.com/hjosugi/frost-build",
        "license": "0BSD",
        "architecture": {
            "64bit": {
                "url": f"{BASE}/v{version}/{windows}",
                "hash": digest,
                "extract_dir": f"frostbuild-v{version}-x86_64-pc-windows-msvc",
            }
        },
        "bin": ["frost.exe", "frostd.exe"],
        "checkver": {"github": "https://github.com/hjosugi/frost-build"},
        "autoupdate": {
            "architecture": {
                "64bit": {
                    "url": f"{BASE}/v$version/frostbuild-v$version-x86_64-pc-windows-msvc.zip",
                    "extract_dir": "frostbuild-v$version-x86_64-pc-windows-msvc",
                }
            },
            "hash": {
                "url": f"{BASE}/v$version/SHA256SUMS",
                "regex": "$sha256\\s+$basename",
            },
        },
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def render(version: str, sums: Path, output: Path) -> None:
    if not VERSION.fullmatch(version):
        raise ValueError(f"{version!r} is not X.Y.Z")
    items = checksums(sums, version)
    rendered_formula = formula(version, items)
    rendered_scoop = scoop(version, items)
    output.mkdir(parents=True, exist_ok=True)
    (output / "frostbuild.rb").write_text(rendered_formula, encoding="utf-8")
    (output / "frostbuild.json").write_text(rendered_scoop, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--checksums", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        render(args.version, args.checksums, args.output)
    except (OSError, ValueError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
